# Bind one declared model/runtime and authenticated direct inputs before any
# expensive mesh or model test. No version, receipt, or wheel identity is inferred
# from a filename or an unchecked test configuration.
include(${CMAKE_CURRENT_LIST_DIR}/../cmake/MpasDependencyPins.cmake)
if(IJEDI_MPAS_TEST_SUITE)
  if(NOT IJEDI_MPAS_TEST_SUITE MATCHES "^(geometry|analysis)$")
    message(FATAL_ERROR "MPAS test suite must be geometry or analysis")
  endif()
  foreach(_required IN ITEMS IJEDI_MPAS_CASE_DIR IJEDI_MPAS_WHEEL
      IJEDI_MPAS_PYTHON IJEDI_MPAS_DIRECT_ORACLE IJEDI_MPAS_RUNTIME_RECEIPT
      IJEDI_MPAS_GEOMETRY_CASES IJEDI_MPAS_GEOMETRY_LOCATIONS)
    if(NOT ${_required} OR NOT EXISTS "${${_required}}")
      message(FATAL_ERROR "Mandatory MPAS release input is missing: ${_required}")
    endif()
  endforeach()
  foreach(_corpus IN ITEMS locations_256.json locations_10000.json)
    if(NOT EXISTS "${IJEDI_MPAS_GEOMETRY_LOCATIONS}/${_corpus}")
      message(FATAL_ERROR "Mandatory MPAS geometry corpus is missing: ${_corpus}")
    endif()
  endforeach()
  if(IJEDI_MPAS_TEST_SUITE STREQUAL "analysis")
    foreach(_required IN ITEMS IJEDI_MPAS_ANALYSIS_LOCATIONS IJEDI_MPAS_CONTRACT_SOURCE_DIR)
      if(NOT ${_required} OR NOT EXISTS "${${_required}}")
        message(FATAL_ERROR "Mandatory MPAS analysis input is missing: ${_required}")
      endif()
    endforeach()
  endif()
endif()
if(IJEDI_MPAS_ANALYSIS_LOCATIONS AND NOT (IJEDI_MPAS_CASE_DIR AND
   IJEDI_MPAS_WHEEL AND IJEDI_MPAS_PYTHON AND IJEDI_MPAS_DIRECT_ORACLE))
  message(FATAL_ERROR "MPAS analysis requires the complete authenticated model input graph")
endif()
if(IJEDI_MPAS_WHEEL)
  file(READ "${IJEDI_MPAS_RUNTIME_RECEIPT}" _mpas_runtime)
  string(JSON IJEDI_MPAS_WHEEL_SHA256 GET "${_mpas_runtime}" mpas_pytorch wheel_sha256)
  string(JSON IJEDI_MPAS_SOURCE_COMMIT GET "${_mpas_runtime}" mpas_pytorch source_commit)
  string(JSON IJEDI_MPAS_PACKAGE_VERSION GET "${_mpas_runtime}" mpas_pytorch version)
  foreach(_component IN ITEMS python torch numpy netcdf4)
    string(TOUPPER "${_component}" _upper_component)
    string(JSON IJEDI_MPAS_${_upper_component}_VERSION GET "${_mpas_runtime}" runtime ${_component})
  endforeach()
  file(SHA256 "${IJEDI_MPAS_WHEEL}" _actual_wheel_sha256)
  if(NOT _actual_wheel_sha256 STREQUAL IJEDI_MPAS_WHEEL_SHA256)
    message(FATAL_ERROR "MPAS wheel differs from the exact runtime receipt")
  endif()
  file(SHA256 "${IJEDI_MPAS_RUNTIME_RECEIPT}" _runtime_sha256)
  set(IJEDI_MPAS_RUNTIME_RECEIPT_SHA256 "${_runtime_sha256}" CACHE INTERNAL
      "Configured runtime input authority" FORCE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${IJEDI_MPAS_RUNTIME_RECEIPT}")
endif()
if(IJEDI_MPAS_CASE_DIR AND IJEDI_MPAS_WHEEL AND IJEDI_MPAS_PYTHON AND
   IJEDI_MPAS_DIRECT_ORACLE)
  file(READ "${IJEDI_MPAS_DIRECT_ORACLE}" _mpas_oracle)
  string(JSON _oracle_wheel GET "${_mpas_oracle}" wheel_sha256)
  string(JSON _oracle_source GET "${_mpas_oracle}" package_source_commit)
  if(NOT _oracle_wheel STREQUAL IJEDI_MPAS_WHEEL_SHA256 OR
     NOT _oracle_source STREQUAL IJEDI_MPAS_SOURCE_COMMIT)
    message(FATAL_ERROR "Direct MPAS oracle has a foreign package identity")
  endif()
  foreach(_component IN ITEMS python torch numpy netcdf4)
    string(TOUPPER "${_component}" _upper_component)
    string(JSON _oracle_version GET "${_mpas_oracle}" runtime ${_component}_version)
    if(NOT _oracle_version STREQUAL IJEDI_MPAS_${_upper_component}_VERSION)
      message(FATAL_ERROR "Direct MPAS oracle has a foreign runtime: ${_component}")
    endif()
  endforeach()
  string(JSON _declared_machine GET "${_mpas_runtime}" runtime machine)
  string(JSON _oracle_machine GET "${_mpas_oracle}" runtime platform_machine)
  if(NOT _declared_machine STREQUAL _oracle_machine)
    message(FATAL_ERROR "Direct MPAS oracle has a foreign architecture")
  endif()
  foreach(_receipt IN ITEMS horizontal_geometry_receipt static_vertical_geometry_receipt
          geometry_bundle_receipt configuration_receipt state_schema_digest)
    string(TOUPPER "${_receipt}" _upper_receipt)
    string(JSON IJEDI_MPAS_${_upper_receipt} GET "${_mpas_oracle}" ${_receipt})
  endforeach()
  foreach(_input IN ITEMS init grid namelist)
    string(JSON _input_name GET "${_mpas_oracle}" input_files ${_input} name)
    string(JSON _input_digest GET "${_mpas_oracle}" input_files ${_input} sha256)
    file(SHA256 "${IJEDI_MPAS_CASE_DIR}/${_input_name}" _actual_input_digest)
    if(NOT _actual_input_digest STREQUAL _input_digest)
      message(FATAL_ERROR "Configured MPAS input differs from direct oracle: ${_input}")
    endif()
  endforeach()
  file(SHA256 "${IJEDI_MPAS_DIRECT_ORACLE}" _oracle_sha256)
  set(IJEDI_MPAS_DIRECT_ORACLE_SHA256 "${_oracle_sha256}" CACHE INTERNAL
      "Configured direct-oracle input authority" FORCE)
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${IJEDI_MPAS_DIRECT_ORACLE}")
endif()
