#!/usr/bin/env python3
# Copyright 2026 IC Weather LLC. Licensed under the Apache License, Version 2.0.
"""Authenticate every locked distribution against retained wheel member bytes.

Installation RECORD is regenerated by pip and is not a wheel-byte oracle. This
check authenticates all other wheel members and the distribution inventory;
the model's separate check additionally authenticates its package inventory.
"""
import argparse
from email.parser import BytesParser
import hashlib
import importlib.metadata as metadata
import json
from pathlib import Path, PurePosixPath
import re
import sysconfig
from zipfile import ZipFile


def canonical(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def read_lock(path):
    records = {}
    for line in Path(path).read_text().splitlines():
        match = re.fullmatch(r"([A-Za-z0-9_.-]+)==([^\s]+) --hash=sha256:([0-9a-f]{64})", line)
        if match is None:
            raise RuntimeError("runtime lock requires one exact version and SHA-256 per line")
        name, version, digest = match.groups()
        name = canonical(name)
        if name in records:
            raise RuntimeError("duplicate locked distribution: " + name)
        records[name] = (version, digest)
    if not records:
        raise RuntimeError("runtime lock is empty")
    return records


def verify_artifacts(requirements, wheelhouse):
    expected = read_lock(requirements)
    installed = {}
    for distribution in metadata.distributions():
        name = canonical(distribution.metadata["Name"])
        if name in installed:
            raise RuntimeError("ambiguous installed distribution: " + name)
        installed[name] = distribution
    if set(installed) != set(expected):
        raise RuntimeError("installed distribution inventory differs from the exact lock")
    # Bind files by digest, not filename or an untrusted installed RECORD.
    retained = {}
    for wheel in sorted(Path(wheelhouse).glob("*.whl")):
        checksum = hashlib.sha256()
        with wheel.open("rb") as stream:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                checksum.update(chunk)
        digest = checksum.hexdigest()
        if digest in retained:
            raise RuntimeError("duplicate retained wheel digest")
        retained[digest] = wheel
    records = {}
    for name, (version, digest) in sorted(expected.items()):
        if digest not in retained or installed[name].version != version:
            raise RuntimeError("missing exact wheel or installed version mismatch: " + name)
        distribution = installed[name]
        wheel = retained[digest]
        checked = 0
        with ZipFile(wheel) as archive:
            members = archive.namelist()
            if len(members) != len(set(members)):
                raise RuntimeError("duplicate wheel members: " + str(wheel))
            for member in members:
                path = PurePosixPath(member)
                if path.is_absolute() or ".." in path.parts or "\\" in member:
                    raise RuntimeError("unsafe wheel member: " + member)
            info = [member for member in members
                    if member.count("/") == 1 and member.endswith(".dist-info/METADATA")]
            if len(info) != 1:
                raise RuntimeError("ambiguous retained wheel metadata")
            header = BytesParser().parsebytes(archive.read(info[0]))
            if (not header["Name"] or canonical(header["Name"]) != name or
                    header["Version"] != version):
                raise RuntimeError("locked wheel metadata mismatch: " + name)
            for member in members:
                if member.endswith(("/", ".dist-info/RECORD")):
                    continue
                if ".data/" in member:
                    scheme, relative = member.split(".data/", 1)[1].split("/", 1)
                    if scheme not in ("data", "purelib", "platlib"):
                        raise RuntimeError("undeclared wheel relocation: " + member)
                    target = Path(sysconfig.get_path(scheme)) / relative
                else:
                    target = Path(distribution.locate_file(member))
                if not target.is_file() or target.read_bytes() != archive.read(member):
                    raise RuntimeError("installed wheel member differs: " + name + ":" + member)
                checked += 1
        records[name] = dict(version=version, wheel_sha256=digest,
                             installed_members_checked=checked)
    return dict(scope="locked_distribution_member_integrity_not_scientific_qualification",
                requirements_sha256=hashlib.sha256(Path(requirements).read_bytes()).hexdigest(),
                distributions=records)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements", type=Path, required=True)
    parser.add_argument("--wheelhouse", type=Path, required=True)
    args = parser.parse_args()
    print(json.dumps(verify_artifacts(args.requirements, args.wheelhouse), sort_keys=True))


if __name__ == "__main__":
    main()
